---
version: "3.8"
services:
  movies:
    img: vinay451/paymovies
    ports:
      - "81:80"
    deploy: replicas:3
  trains:
    img: vinay451/paytrains
    ports:
      - "82:80"
    deploy: replicas:3
recharge:
  img: vinay451/payrecharge
  ports:
    - "83:80"
  deploy: replicas:3
dth:
  img: vinay451/paydth
  ports:
    - "84:80"
  deploy: replicas:3
